# -*- coding: utf-8 -*-
#
# This file is part of Flask-Gravatar
# Copyright (C) 2015, 2017 CERN.
# Copyright (C) 2018 Swiss Data Science Center (SDSC)
# A partnership between École Polytechnique Fédérale de Lausanne (EPFL) and
# Eidgenössische Technische Hochschule Zürich (ETHZ).
#
# Flask-Gravatar is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.


[pytest]
addopts = --doctest-glob="*.rst" --doctest-modules --cov=flask_gravatar --cov-report=term-missing
# Removed '--pep8' flag (Obsolete, caused errors after removing pytest-pep8 plugin).
# Removed pep8ignore (Obsolete option tied to the removed pytest-pep8 plugin).
# Removed testpaths (Redundant; pytest relies on the command line or defaults).
